Pin rake to under v11.0
`rake` command makes following error:

```
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000000ff9f88>
```

Since Rake 11.0.1 removes the last_comment method which other gem uses,
to avoid to get the error we have to pin rake's version.

REF:

- https://github.com/ruby/rake/blob/ed197e56cc626725f02431d909e02e048244488e/lib/rake/task_manager.rb#L8
- http://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11